[package]
name = "num256"
version = "0.1.0"
authors = ["Jehan <jehan.tremback@gmail.com>"]
license = "Apache 2.0"

[dependencies]
num = "0.2"
serde = "1.0.70"
failure = "0.1.3"
num-derive = "0.2"
num-traits = "0.2.6"
serde_derive = "1.0.80"

[dev-dependencies]
serde_derive = "1.0.70"
serde_json = "1.0.24"
lazy_static = "1.0.2"
